### ISSUE TITLE
Feature request: Relative value for proximity sensor instead of fixed?

### ISSUE THREAD

**Issue by jeroenvdd** [seaky/nspanel_pro_tools_apk#12] opened 2023-03-11 18:32 UTC
hey,
first of all: thx for the tools they are working great, you have increased the WAF of my devices greatly.

the only thing I'd like to 'change' is at the moment you have to set a value for the proximity sensor,
but people (incl me) have noticed the sensor tends to have runout?

so for me i set it to 1020 it works for 5 days, but then suddenly my baseline is 1025 and it's always triggered,
at that point : i press home button through adb, change the value and proceed.

Would it be possible to set it to 'power screen on' if fe. past 5min average value increased with 40.

this way the runout is handled permanently and not dependant on env conditions..

thx in advance!

**Comment by seaky** [comment] 2023-03-11 20:22
Hi,

What do you mean “it’s always  triggered”? You cant wake up your device with the sensor?

Thx,
Robi

**Comment by jeroenvdd** [comment] 2023-03-14 17:52
wel the runout with me is the following Day one no one in front of screen distance value 1020 so i set trigger to 1050.
three days later -> no one in front of screen distance value -> 1055.

so it's always triggered cause the distance has run out.

I've also read peoples sensor doing the opposite and thus never reaching the threshold :)

**Comment by thoml95** [comment] 2023-04-27 21:55
> I've also read peoples sensor doing the opposite and thus never reaching the threshold :)

Yep, i´m one of them. For me it Shows a high Value close to the Panel and at idle a value of around 20-30cm.

**Comment by seaky** [comment] 2023-04-28 11:05
Generally the proximity sensors are designed to sense short distance obstacles. This type of sensors are not able to detect human presence consequently setting the trigger value around the idle value or just slightly lower than the idle it is not the right usage. It can detect gestures some cm far from the sensor under 10-5cm. Thats why I called it hand-"wave".
Furthermore the sensors accuracy can only be interpreted in the sensor working range/point which is as I mentioned aprox some cm.

So always set the trigger point based on your hand-wave as close as possible. And the value is relevant  because it depends on temp and actual sensor manufacturer. In the working range it should be consistent.

**Comment by jeroenvdd** [comment] 2023-05-04 16:30
> Generally the proximity sensors are designed to sense short distance obstacles. This type of sensors are not able to detect human presence consequently setting the trigger value around the idle value or just slightly lower than the idle it is not the right usage. It can detect gestures some cm far from the sensor under 10-5cm. Thats why I called it hand-"wave". Furthermore the sensors accuracy can only be interpreted in the sensor working range/point which is as I mentioned aprox some cm.
> 
> So always set the trigger point based on your hand-wave as close as possible. And the value is relevant because it depends on temp and actual sensor manufacturer. In the working range it should be consistent.

the issue with me isn't really about the 'distance of detection' its that if given time the sensor wanders off so much that the gap between 'far' and almost touching the screen has changed.

FE when i made the post no one infront of screen was 1020 waving hand right infront of sensor 1140 ish so i could have indeed set it to 1135 requiring my hand to be almost on the screen..

but today I had the issue again and my 'no one in front of screen value' is 1300 no where near the previous trigger / even higher then i could previously 'trigger' it

**Comment by seaky** [comment] 2023-05-04 16:46
Yep I got it, your problem is different I assume that your case rather caused by sensor drifting.
Can you observe the unit for some day and check the sensor value?
- is the value constantly increasing or fully random?
- what happens after restart?

offtopic
Currently I’m moving to a new flat when we ‘settled down’ I’ll switch back to this project

**Comment by SGXander** [comment] 2023-05-05 16:54
I'd like to add that both of the units I have do the same thing. Possibly ambient light affects the sensor as it's a much closer wave required at night than in the day.
________________________________

**Closed** 2024-11-16 00:07 UTC
