### ISSUE TITLE
v2.3.0 crashes on devices other than NSPanel Pro, such as my S6E.

### ISSUE THREAD

**Issue by maodun96** [seaky/nspanel_pro_tools_apk#156] opened 2024-11-19 03:05 UTC
After installing the new version of the app, the app crashes when the main switch is turned on.

If the old version of the app with the main switch turned on is upgraded to the new version, the app will crash immediately. Reinstalling the old version will restore functionality.

Looking at the logs, it seems to be caused by the lack of an integrated local MQTT server on the device.

Attached are the relevant log files.

[debug.log](https://github.com/user-attachments/files/17808694/debug.log)

**Comment by evil-dog** [comment] 2024-11-19 05:44
I have a T6E and seeing the exact same issue with very similar debug log.

Wonder if installing one of the Sonoff OTAs would fix this?

**Comment by seaky** [comment] 2024-11-19 06:50
Hi,

Could you please attach a longer log file? Becaue the connection error should not cause crash, instead it should display "offline". 
The crash should be caused by something else.

Thx

**Comment by seaky** [comment] 2024-11-19 07:15
I could reproduce the issue, will be solved soon...

**Comment by maodun96** [comment] 2024-11-19 10:29
> Hi,
> 
> Could you please attach a longer log file? Becaue the connection error should not cause crash, instead it should display "offline". The crash should be caused by something else.
> 
> Thx
The previous log contained everything from startup to crash, but here is a more detailed version.

I repeated the application startup multiple times, and you can distinguish the different instances by the time gaps.
[debug.log](https://github.com/user-attachments/files/17813630/debug.log)

**Comment by jengel84** [comment] 2024-11-20 09:11
For me the new version also crashes on NS Panel Pro. Do you need another log?
Looking forward to your fix

**Comment by kwetnico** [comment] 2024-11-20 10:05
Hello, i have same problem on nspanel pro 120 (crash on startup) and impossible to install version 2.2.4 to restore operation.

**Comment by jengel84** [comment] 2024-11-20 10:19
> Hello, i have same problem on nspanel pro 120 (crash on startup) and impossible to install version 2.2.4 to restore operation.

I could not downgrade first neither. What helped for me, was to add "-d" to the install prompt in front of the file name. Did you try that?

```

adb install -r -d nspanel-pro-tools-2.2.4-release.apk

```

**Comment by seaky** [comment] 2024-11-20 10:23
Remove new manually from screen. You can delete it by adb because it has DeviceAdmin privileges!

**Comment by seaky** [comment] 2024-11-20 10:28
I"m working on the solution today I'll release a partial fix. It is not related to new devices it is related to mqtt-client what I heavily modified.

For NSPanel users you can turn of mqtt connection via mqtt-enable key in shared properties.
For S6E and T6E users you have to downgrade it manually

Sorry for that!

The issue is popping up when the mqtt server is not available also for zigbee and also for general mqtt. In the reconnection I accidentally nulls an object thats why the registerBroadcast is failing.

**Comment by kwetnico** [comment] 2024-11-20 10:33
> Remove new manually from screen. You can delete it by adb because it has DeviceAdmin privileges!

If you deliver a fix today I will wait and install over it.
Thanks

**Comment by seaky** [comment] 2024-11-20 15:53
fixed in v2.3.1

**Comment by kwetnico** [comment] 2024-11-20 15:56
> fixed in v2.3.1

I just installed it and the app still refuses to open

**Comment by seaky** [comment] 2024-11-20 15:57
could you please attach logs

**Comment by seaky** [comment] 2024-11-20 15:58
I'm tested on two nspanel120 and 5 nspanel 86 without any issue

**Comment by kwetnico** [comment] 2024-11-20 15:58
> could you please attach logs

How to find log files to send them?

**Comment by seaky** [comment] 2024-11-20 16:02
```
adb shell "ps -A | grep com.seaky.nspanelpro"
adb logcat -d --pid=<pid>

```

the ps second value of the result is the pid

**Comment by kwetnico** [comment] 2024-11-20 16:04
Same problem after reboot nspanel pro 120 (in french) 
![20241120_170330](https://github.com/user-attachments/assets/681c2318-3992-4b9b-a9d8-273a683e65d2)

**Comment by jengel84** [comment] 2024-11-20 16:14
> adb logcat -d --pid=<pid>

zsh: parse error near `\n'

is this what you need?

**Comment by kwetnico** [comment] 2024-11-20 16:14
> adb logcat -d --pid=<pid>

Not result : 
![image](https://github.com/user-attachments/assets/71c9112e-95a5-4e78-b400-a96480966a16)

**Comment by seaky** [comment] 2024-11-20 16:18
I'm not aware of that if you do not click to anything the pid is still available, try it please!

Another solution is to copy the last some minutes of the adb logcat -d result, you have to wait a bit beacuse logcat log could be very long

**Comment by kwetnico** [comment] 2024-11-20 16:20
> I'm not aware of that if you do not click to anything the pid is still available, try it please!
> 
> Another solution is to copy the last some minutes of the adb logcat -d result, you have to wait a bit beacuse logcat log could be very long

Adb result : 
[adb_result.txt](https://github.com/user-attachments/files/17833640/adb_result.txt)

**Comment by jengel84** [comment] 2024-11-20 16:23
[log.txt](https://github.com/user-attachments/files/17833671/log.txt)

**Comment by seaky** [comment] 2024-11-20 16:24
I found the issue... I'm checking...

**Comment by seaky** [comment] 2024-11-20 16:40
you should rename zip to apk

**Comment by seaky** [comment] 2024-11-20 16:51
The issue was in connection with the Scheduled Reboot you both use this feature!

**Comment by seaky** [comment] 2024-11-20 16:54
I fixed it in v2.3.1 version also, and now it is available

**Comment by jengel84** [comment] 2024-11-20 17:00
> The issue was in connection with the Scheduled Reboot you both use this feature!

again? :)
Great work - thanks for the quick fix!

**Comment by seaky** [comment] 2024-11-20 17:05
https://github.com/seaky/nspanel_pro_tools_apk/issues/113
yep, always the scheduled reboot... poor stepchild

I did not write a unit test for this beacuse it is too simple... :)

**Comment by jengel84** [comment] 2024-11-20 17:09
okay - next thing.
Maybe off topic:

zigbee displays paired on NSPanel, but does not show up in z2m. Is this to be expected?

**Comment by seaky** [comment] 2024-11-20 17:18
In router mode with z2m 1.41 it is paired as NSPanelP-Router

**Comment by seaky** [comment] 2024-11-20 17:20
I also tested the router mode and it took over quite smartly the devices

**Comment by seaky** [comment] 2024-11-20 17:24
I haven't tested this yet, but you might need to restart the device when switching modes.

**Comment by seaky** [comment] 2024-11-23 07:50
> okay - next thing.
> 
> Maybe off topic:
> 
> 
> 
> zigbee displays paired on NSPanel, but does not show up in z2m. Is this to be expected?
> 
> 

Check out this:

https://github.com/seaky/nspanel_pro_tools_apk/issues/160

**Closed** 2024-12-01 21:02 UTC
Labels: bug, implemented, planned to v2.3.1
